In [1]:
import torch
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [2]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [3]:
x.shape


torch.Size([2, 5])

In [4]:
y = torch.rand([2,5])
y

tensor([[0.5505, 0.4267, 0.3727, 0.5342, 0.1876],
        [0.8873, 0.9219, 0.4044, 0.0228, 0.2340]])

In [5]:
y.view([1,10])

tensor([[0.5505, 0.4267, 0.3727, 0.5342, 0.1876, 0.8873, 0.9219, 0.4044, 0.0228,
         0.2340]])